version: "3"
services:
  php:
    container_name: "${APP_NAME}_php"
    build:
      context: ./php-7-4-fpm-nginx
    volumes:
      - ./app:/var/www/app
      - ./supervisor:/etc/supervisor/conf.d
      - ./shell-scripts:/usr/shell-scripts
      - ./cron-logs/cron.log:/var/log/cron.log
    networks:
      - php
      - mysql
      - rabbitmq
    depends_on:
      - mysql
    # "Wait" for the mysql server to be ready to accept connections
    healthcheck:
      test: mysqladmin ping -h mysql -u $MYSQL_USER --password=$MYSQL_PASSWORD
      interval: 1m30s
      timeout: 30s
      retries: 10

    entrypoint: [ bash, -c, "/usr/shell-scripts/init.sh" ]
  nginx:
    container_name: "${APP_NAME}_nginx"
    image: nginx:1.17.9
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php
    depends_on:
      - php
      - mysql
  mysql:
    container_name: "${APP_NAME}_mysql"
    image: mysql:5.7
    # Fix Error: ER_NOT_SUPPORTED_AUTH_MODE:
    # Client does not support authentication protocol requested by server;
    # consider upgrading MySQL client
    command: [--default-authentication-plugin=mysql_native_password]
    restart: always
    ports: 
      - "${MYSQL_PORT}:3306"
    volumes: 
      - ./.data/mysql:/var/lib/mysql
    networks:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  rabbitmq: 
    container_name: "${APP_NAME}_rabbitmq"
    hostname: rabbit
    image: rabbitmq:3.10.8-management
    environment: 
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER} 
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes: 
      - ./.data/rabbitmq/:/var/lib/rabbitmq
    networks:
      - rabbitmq
    ports: 
      - "5672:5672" 
      - "${RABBITMQ_WEB_PORT}:15672"
networks:
  php: 
  mysql:
  rabbitmq:
